services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    ports:
      - "5433:5432"       # Puerto local:puerto contenedor
    volumes:
      - db_reservation:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin2
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db_reservations  # Base de datos inicial que quieres crear

volumes:
  db_reservation: